name: windowsservervps

on: workflow_dispatch

jobs:
  build:
    runs-on: windows
    steps:
    - name: Download Ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract Ngrok Archive
      run: Expand-Archive ngrok.zip
    - name: Auth
      run: .\ngrok\ngrok.exe authtoken $Env:2KYKI4ERtBcWIGqZa1l9HKGiiF8_5sdDBRqPvnCYizm4BGu6g
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 5
    - run: Set-LocalUser -Name "admin" -Password (ConvertTo-SecureString -AsPlainText "1234567890." -Force)
    - name: Start Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
      
    
